### ISSUE TITLE
about the env

### ISSUE THREAD

**Issue by LighteningDarkness** [lxq1000/Faceptor#5]
Hi! I am interested in your amazing work but i met some problems when installing needed packages. Could you please release a list of needed packages or requirements.txt? Thank you!

**Comment by SebastianRegalado** [comment]
Hi @LighteningDarkness, were you able to resolve the dependencies? I'm having problems running the code too

**Comment by LighteningDarkness** [comment]
> Hi @LighteningDarkness, were you able to resolve the dependencies? I'm having problems running the code too

not yet...i met new problems

**Comment by cscpyy-wen** [comment]
Hi！I can't find the library called "blueprint.ml.augmenters". Gemini tells me it's your private library but you haven't open-sourced it.
